spring.application.name=backend
server.port=8081

# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/jo_dakar_db
spring.datasource.username=postgres
spring.datasource.password=2412

# Hibernate & JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html